USE [DuAnQLNS]


		--1--
CREATE TABLE TAIKHOAN (
    IDTAIKHOAN NVARCHAR(50) NOT NULL,                                      
    TENTAIKHOAN NVARCHAR(100), 
    MATKHAU NVARCHAR(50),
    CONSTRAINT PK_TAIKHOAN PRIMARY KEY (IDTAIKHOAN),
);

		--2--
CREATE TABLE PHONGBAN (
    IDPB NVARCHAR(50) NOT NULL,  
    TENPB NVARCHAR(100), 
    SOLUONGNVPB INT,
    MOTAPB NVARCHAR(255),
    CONSTRAINT PK_PHONGBAN PRIMARY KEY (IDPB)
);

		--3--
CREATE TABLE DUAN (
    IDDA NVARCHAR(50) NOT NULL,
    TENDA NVARCHAR(100),
    SOLUONGNVDA INT NOT NULL,
    MOTADA NVARCHAR(255) NOT NULL,
    CONSTRAINT PK_DUAN PRIMARY KEY (IDDA)
);

		--4--
CREATE TABLE NHANVIEN (
    IDNV NVARCHAR(50) NOT NULL,
    TENNV NVARCHAR(100),
    NGAYSINH DATE,
    DIACHI NVARCHAR(255),
    LUONG INT NOT NULL,
    IDPB NVARCHAR(50) NOT NULL,
    IDDA NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (IDNV),
    CONSTRAINT FK_NHANVIEN_DUAN FOREIGN KEY (IDDA) REFERENCES DUAN (IDDA),
    CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (IDPB) REFERENCES PHONGBAN (IDPB)
);

		--5--
CREATE TABLE PHANCONG (
    IDNV NVARCHAR(50) NOT NULL,
    IDDA NVARCHAR(50) NOT NULL,
    VAITRO NVARCHAR(100),
    CONSTRAINT PK_PHANCONG PRIMARY KEY (IDNV, IDDA),
    CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (IDNV) REFERENCES NHANVIEN (IDNV),
    CONSTRAINT FK_PHANCONG_DUAN FOREIGN KEY (IDDA) REFERENCES DUAN (IDDA)
);

		--6--
CREATE TABLE LUONG (
    IDLUONG INT IDENTITY NOT NULL,
    NGAYBD DATE,
    NGAYKT DATE,
    SONGAYNGHI INT,
    TONGLUONG INT NOT NULL,
    IDNV NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_LUONG PRIMARY KEY (IDLUONG),
    CONSTRAINT FK_LUONG_NHANVIEN FOREIGN KEY (IDNV) REFERENCES NHANVIEN (IDNV),
	);

		--7--
IF OBJECT_ID('USP_GetLuongWithNhanVien', 'P') IS NOT NULL
    DROP PROCEDURE USP_GetLuongWithNhanVien;
GO
CREATE PROCEDURE USP_GetLuongWithNhanVien
AS
BEGIN
    SELECT 
        L.IDLUONG,
        L.NGAYBD,
        L.NGAYKT,
        L.SONGAYNGHI,
        L.TONGLUONG,
        NV.TENNV,
        NV.LUONG
    FROM 
        LUONG L
    JOIN 
        NHANVIEN NV ON L.IDNV = NV.IDNV;
END;
GO

		--8--
CREATE TABLE LOAIHOPDONG (
	IDLOAIHD NVARCHAR(50) NOT NULL,
	TENLOAIHD NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOAIHOPDONG PRIMARY KEY (IDLOAIHD)
);

		--9--
CREATE TABLE TRANGTHAIHOPDONG (
	IDTRANGTHAI NVARCHAR(50) NOT NULL,
	TENTRANGTHAI NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_TRANGTHAIHOPDONG PRIMARY KEY (IDTRANGTHAI)
);

		--10--
CREATE TABLE HOPDONG (
    IDHD NVARCHAR(50) NOT NULL,
    NGAYBDHD DATE,
    NGAYKTHD DATE,
    MOTAHD NVARCHAR(MAX) NOT NULL,
    IDNV NVARCHAR(50) NOT NULL,
    IDLOAIHD NVARCHAR(50) NOT NULL,
    IDTRANGTHAI NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_HOPDONG PRIMARY KEY (IDHD),
    CONSTRAINT FK_HOPDONG_NHANVIEN FOREIGN KEY (IDNV) REFERENCES NHANVIEN (IDNV),
    CONSTRAINT FK_HOPDONG_LOAIHOPDONG FOREIGN KEY (IDLOAIHD) REFERENCES LOAIHOPDONG (IDLOAIHD),
    CONSTRAINT FK_HOPDONG_TRANGTHAIHOPDONG FOREIGN KEY (IDTRANGTHAI) REFERENCES TRANGTHAIHOPDONG (IDTRANGTHAI), 
);

		--11--
IF OBJECT_ID('USP_GetHopDongWithDetails', 'P') IS NOT NULL
    DROP PROCEDURE USP_GetHopDongWithDetails;
GO
CREATE PROCEDURE USP_GetHopDongWithDetails
AS
BEGIN
    SELECT 
        HD.IDHD,
        HD.NGAYBDHD,
        HD.NGAYKTHD,
        HD.MOTAHD,
        NV.TENNV AS TenNhanVien, -- Lay tên nhân viên tu bang NHANVIEN
        LH.TENLOAIHD AS LoaiHopDong, -- Lay tên loai hop dong tu bang LOAIHOPDONG
        TT.TENTRANGTHAI AS TrangThaiHopDong -- Lay trang thái hop dong tu bang TRANGTHAIHOPDONG dat as de de nhìn
    FROM 
        HOPDONG HD
    JOIN 
        NHANVIEN NV ON HD.IDNV = NV.IDNV
    JOIN 
        LOAIHOPDONG LH ON HD.IDLOAIHD = LH.IDLOAIHD
    JOIN 
        TRANGTHAIHOPDONG TT ON HD.IDTRANGTHAI = TT.IDTRANGTHAI;
END;
GO

		--12--
INSERT INTO LOAIHOPDONG( IDLOAIHD,TENLOAIHD)
VALUES ('L001', N'Chính Thức');
INSERT INTO LOAIHOPDONG( IDLOAIHD,TENLOAIHD)
VALUES ('L002', N'Thử Việc');
INSERT INTO LOAIHOPDONG( IDLOAIHD,TENLOAIHD)
VALUES ('L003', N'Thời Vụ');
INSERT INTO TRANGTHAIHOPDONG( IDTRANGTHAI,TENTRANGTHAI)
VALUES ('TT1', N'Hiệu Lực');
INSERT INTO TRANGTHAIHOPDONG( IDTRANGTHAI,TENTRANGTHAI)
VALUES ('TT2', N'Hết Hạn');
INSERT INTO TRANGTHAIHOPDONG( IDTRANGTHAI,TENTRANGTHAI)
VALUES ('TT3', N'Kết Thúc');
INSERT INTO TRANGTHAIHOPDONG( IDTRANGTHAI,TENTRANGTHAI)
VALUES ('TT4', N'Chưa Gia Hạn');
select * from LOAIHOPDONG
EXEC USP_GetHopDongWithDetails

		--13--
IF OBJECT_ID('USP_GetNhanVienWithPhongBanAndDuAn', 'P') IS NOT NULL
    DROP PROCEDURE USP_GetNhanVienWithPhongBanAndDuAn;
GO

CREATE PROCEDURE USP_GetNhanVienWithPhongBanAndDuAn
AS
BEGIN
    SELECT 
        NV.IDNV,
        NV.TENNV,
        NV.NGAYSINH,
        NV.DIACHI,
        NV.LUONG,
        PB.TENPB,
        DA.TENDA,
        PC.VAITRO  
    FROM 
        NHANVIEN NV
    JOIN 
        PHONGBAN PB ON NV.IDPB = PB.IDPB
    JOIN 
        PHANCONG PC ON NV.IDNV = PC.IDNV  
    JOIN 
        DUAN DA ON PC.IDDA = DA.IDDA;  
END;
GO

exec USP_GetNhanVienWithPhongBanAndDuAn
select *from NHANVIEN
select *from PHANCONG 
select *from HOPDONG
select *from LUONG
select *from DUAN